import gzip,hashlib,json,shutil,tarfile
from pathlib import Path
repo=Path('/workspace/partitionline');base='12f4398662044947ae653f07923290127457f2ef';original=repo/'docs/evidence/broker/KL11-37/production/development/socket-after-jwks-12f43986';out=repo/'docs/evidence/broker/KL11-37/production/development/socket-after-jwks-12f43986-after-stop-01';packet=repo/'docs/evidence/broker/KL11-37/production/socket-checkpoint-after-jwks-12f43986';packet.mkdir(exist_ok=True);commands=json.loads((out/'commands.json').read_text())['commands'];checks=json.loads((out/'source-per-command.json').read_text())['checks'];assert len(commands)==24 and len(checks)==48
for row in commands:
 assert row['exit_code']==0 and not row['resource_holds'];assert hashlib.sha256((out/row['log']).read_bytes()).hexdigest()==row['sha256']
behavior=[row['test_totals']for row in commands if'test_totals'in row];assert len(behavior)==10 and sum(row['passed']for row in behavior)==812;assert all(row[k]==0 for row in behavior for k in['failed','ignored','measured','filtered'])
assert all(row['files']==69146 and row['bytes_and_full_modes_identical']for row in checks);assert len(set(row['aggregate_sha256']for row in checks))==1
invocations=[]
for row in commands:
 manifest=json.loads((out/(row['label']+'-executed-ELFs.json')).read_text())
 for item in manifest['invocations']:
  p=Path(item['retained_path']);assert hashlib.sha256(p.read_bytes()).hexdigest()==item['sha256']and p.stat().st_mode&0o777==item['full_mode'];invocations.append(dict(command=row['label'],**item))
assert len(invocations)==50
retention=Path('/workspace/work/broker-oidc/socket-executed-retention-12f43986');retention.mkdir(exist_ok=True);archive=retention/'all50-executed-test-invocations.tar.gz'
with tarfile.open(archive,'w:gz',compresslevel=6)as tar:
 for row in invocations:tar.add(row['retained_path'],arcname=row['command']+'/'+Path(row['retained_path']).name,recursive=False)
with tarfile.open(archive,'r:gz')as tar:
 for row in invocations:
  name=row['command']+'/'+Path(row['retained_path']).name;member=tar.getmember(name);assert hashlib.sha256(tar.extractfile(member).read()).hexdigest()==row['sha256']and member.mode&0o777==row['full_mode']
(out/'bin').mkdir(exist_ok=True);(out/'bin/all-executed-manifest.json').write_text(json.dumps(dict(archive_local_path=str(archive),archive_sha256=hashlib.sha256(archive.read_bytes()).hexdigest(),archive_bytes=archive.stat().st_size,actual_invocations=50,bytes_and_full_modes_roundtrip=True,invocations=invocations),indent=2)+'\n')
old=json.loads((repo/'docs/evidence/broker/KL11-37/production/socket-checkpoint-source20/manifest.json').read_text());source=[]
for row in old['source']:
 data=(repo/row['path']).read_bytes();assert hashlib.sha256(data).hexdigest()==row['sha256'];p=packet/row['path'];p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(data);p.chmod(0o644);source.append(row)
producer=out/'producer';producer.mkdir(exist_ok=True)
for name in ['prepare-socket-after-jwks.py','run-socket-focus.py','clear-final-socket-cache.py','seal-socket-source20.py']:shutil.copy2('/workspace/work/broker-oidc/'+name,producer/name)
profile={row['label']:row['test_totals']for row in commands if'test_totals'in row};minimum=min(row['minimum_sampled_free_bytes']for row in commands);assert minimum>=350*1024*1024
original_commands=json.loads((original/'commands.json').read_text())['commands'];assert len(original_commands)==8 and all(row['exit_code']==0 for row in original_commands);interrupted=json.loads((original/'resource-interruption-01.json').read_text());source_after=json.loads((original/'source-after-interruption.json').read_text());assert source_after['aggregate_sha256']==checks[0]['aggregate_sha256']
cleanup=json.loads((out/'cache-clear-final/receipt.json').read_text());assert not Path('/workspace/work/broker-oidc/target').exists()and cleanup['all_ELF_bytes_and_full_modes_roundtrip_verified']
validation=dict(base_source_sha=base,candidate_source_sha=None,scope='exact pushed JWKS source plus six unchanged frozen source20 overlays; development qualification before actual socket source push; selected owned behavior and full all-target lint, not whole broker test matrix or live SDK proof',source=source,runtime_commands=24,all_pass=True,unfiltered_behavior={'passed':812,'failed':0,'ignored':0,'filtered':0},behavior_by_profile=profile,strict_all_target_cells=10,fmt_and_toolchain_cells=4,full_source_files=69146,before_after_full_byte_mode_checks=48,aggregate_source_sha256=checks[0]['aggregate_sha256'],executed_ELF_invocations_retained=50,executed_ELF_archive_sha256=hashlib.sha256(archive.read_bytes()).hexdigest(),final_cache_ELF_paths_retained=160,final_cache_deleted_only_generated=True,minimum_sampled_free_bytes=minimum,disk_sampling_s=0.5,resource_holds_in_completed_cohort=0,prior_attempt={'prefix':str(original.relative_to(repo)),'completed_commands':8,'passing_behavior_cases':191,'interrupted_command':'stable-sasl-tls-tests','interruption_classification':'shared filesystem disk guard, compiled command safely terminated before behavioral assertions; not a product failure','guard_observed_breach':interrupted['observed_free_samples'],'minimum_limitation':interrupted['minimum_free_scope'],'all148_current_ELF_files_retained_then_own_cache_cleared':True,'all_source_bytes_modes_unchanged_after_interruption':True},live_peer_qualification=False,full_KL11_37_status='open',session_lifetime_ms=0)
(out/'validation.json').write_text(json.dumps(validation,indent=2)+'\n')
packet_manifest=dict(stage='frozen six-source socket checkpoint ready for coordinator source push; full actual-pin gates and genuine peers remain pending',base_source_sha=base,source=source,developer_focus=str((out/'validation.json').relative_to(repo)),developer_validation_sha256=hashlib.sha256((out/'validation.json').read_bytes()).hexdigest(),qualification='24-command active/inactive profile development overlay only',live_peer_qualification=False,session_lifetime_ms=0);(packet/'manifest.json').write_text(json.dumps(packet_manifest,indent=2)+'\n')
(out/'README.md').write_text('''The six OAuth socket source20 files are unchanged and layered over pushed JWKS checkpoint `12f4398662044947ae653f07923290127457f2ef`. The complete source packet contains 69,146 files. Forty-eight checks verify every file byte and full mode before and after the fresh cohort's 24 commands; every check has the same aggregate digest.

Stable Rust and Rust 1.85 each pass the default, TLS, SASL, SASL+TLS and OIDC feature profiles. Selected library and owned HTTP/public-validation/OAuth/SASL socket behavior totals 812 cases, with no failures, ignored cases or filtering. All ten strict all-target Clippy cells, both formatting checks and both toolchain-identification commands pass. Inactive OIDC/SASL integration targets execute zero tests where their feature gates remove their bodies; the TLS-only profile explicitly checks the inactive SASL path. This is not a whole-broker integration test matrix.

Nine OAuth tests per active toolchain use real TLS sockets and signed tokens: installed 3/6 API profiles, authentication versions and legacy tokens, redacted terminal challenge/ACK handling, admission deadlines, token expiry/reconnect, key replacement, revocation during queued/active work and blocked writes, and typed issuer/subject administration authority. Existing sixteen TLS SASL socket tests and the HTTP/public validation suites remain included.

The earlier attempt passed eight commands (191 behavior cases) before the disk guard paused the SASL+TLS compile below 350 MiB. It was safely terminated and its logs, executed binaries, all 148 current ELF files and source-after-interruption proof remain in the separate original prefix. No behavioral assertion failed in that interrupted compile. The first monitor did not persist a complete historical minimum; exact observed breach samples and that limitation are retained. The fresh cohort logs its half-second disk samples/minima and has no holds.

All fifty actual test-executable invocations were copied and byte/mode verified immediately after each command, then losslessly archived. All 160 remaining generated-cache ELF files, including relocatable objects, were separately archived and verified before the cache was removed. Proc exe/cwd/cmdline/environment checks found no live references. Only the owned generated target was removed; source, logs, evidence and WAL were retained.

The frozen six-source packet is ready for a coordinator source checkpoint. Actual pushed-source broker gates and independent genuine Java/C/Rust OAuth client plus HTTPS authority lifecycle qualification remain pending. KL11-37 remains open; live reauthentication is KL11-71 and the session lifetime response remains zero.
''')
for directory in [original,out,packet]:
 paths=sorted(p for p in directory.rglob('*')if p.is_file()and p.name!='SHA256SUMS');(directory/'SHA256SUMS').write_text(''.join(hashlib.sha256(p.read_bytes()).hexdigest()+'  '+str(p.relative_to(directory))+'\n'for p in paths))
print(json.dumps(dict(validation_sha256=hashlib.sha256((out/'validation.json').read_bytes()).hexdigest(),fresh_checksum_manifest_sha256=hashlib.sha256((out/'SHA256SUMS').read_bytes()).hexdigest(),original_checksum_manifest_sha256=hashlib.sha256((original/'SHA256SUMS').read_bytes()).hexdigest(),packet_manifest_sha256=hashlib.sha256((packet/'manifest.json').read_bytes()).hexdigest(),minimum_sampled_free_bytes=minimum,profiles=profile,source_packet_files=len(source)),indent=2))
