import hashlib,json,pathlib,re,os
os.umask(0o077);os.sched_setaffinity(0,{2,4});R=pathlib.Path(__file__).parent;B=R.with_name('tcp-qualification-03');handoff=B/'handoff.json';assert hashlib.sha256(handoff.read_bytes()).hexdigest()=='c745ffa88433439b7e3d785be8c64a0d81ec936e413c029f94160f34a98507cf'
for row in json.loads(handoff.read_bytes())['rows']:
 p=pathlib.Path(row['source']);assert hashlib.sha256(p.read_bytes()).hexdigest()==row['sha256'] and p.stat().st_size==row['bytes'] and p.stat().st_mode&0o7777==row['full07777']
p=R/'candidate/partitionline-broker/src/raft/runtime.rs';new=p.read_text();old=(B/'candidate/partitionline-broker/src/raft/runtime.rs').read_text();marker='#[cfg(test)]\nmod ownership_tests {';assert old.split(marker)[0]==new.split(marker)[0]
start=new.index('async fn abandoned_vote_vector_and_full_route_release_every_exact_correlation');end=new.index('#[tokio::test',start+10);body=new[start:end];assert '.is_err()' not in body and 'abandoned-vector-genuine-grant' in body and 'full-route-genuine-grant' in body and '.fixture("next-campaign-tick"' in body
assert 'Err(Error::Node(replication::Error::InvalidPeer))' in new and 'tokio::time::timeout_at(deadline, self.control.reliable(command))' in new
prior=(B/'candidate/partitionline-broker/tests/common/raft_runtime.rs').read_text();p=R/'candidate/partitionline-broker/tests/common/raft_runtime.rs';current=p.read_text();assert prior.count('Duration::from_secs(15)')==current.count('Duration::from_secs(15)')==4
labels=re.findall(r'\.commit\(\s*"([a-z-]+)"',current);assert len(labels)==11 and len(set(labels))==11
receipt=dict(schema_version=1,scope='source-only hosted test correction; not compiled/executed',runtime_sha256=hashlib.sha256((R/'candidate/partitionline-broker/src/raft/runtime.rs').read_bytes()).hexdigest(),shared_body_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),runtime_prefix_through_all_production_and_prior_cfg_helpers_unchanged_vs03=True,prior03_all29_full_modes_payloads_unchanged=True,typed_invalid_peer_excludes_Deadline_Closed=True,durable_state_rejection_fields=['persistent_election','role','base_position','last_position','committed_end','active_term','wal_durable_ops','election_durable_states','ready','poisoned'],fixture_wait='new absolute2s outer test wait around reliable; production deadlines and20ms intentional Stop/expired-write behavior unchanged',commit_timeout_ms=15000,all_prior15s_values_unchanged=True,commit_phase_labels=labels,diagnostics='on existing timeout only, configured child process status+next_control and <=2048B state firstline; overall text<=16KiB',actual_rust_tests_executed=0,remote_failure_exact_causal_stage_not_established=True)
(R/'source-controls.json').write_text(json.dumps(receipt,indent=2)+'\n');print('Source-only typed rejection, bounded fixture wait, unchanged production/15s and11phase controls PASS.')
