process.roles=broker,controller
node.id=147
controller.quorum.voters=147@127.0.0.1:34291
listeners=PLAINTEXT://127.0.0.1:47131,CONTROLLER://127.0.0.1:34291
advertised.listeners=PLAINTEXT://127.0.0.1:47131
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
controller.listener.names=CONTROLLER
inter.broker.listener.name=PLAINTEXT
log.dirs=/workspace/work/bench-history/native/data
num.network.threads=2
num.io.threads=4
background.threads=2
num.partitions=2
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
group.initial.rebalance.delay.ms=0
auto.create.topics.enable=false
