from pathlib import Path
p=Path('/workspace/work/client-sticky-implementation-prep/candidate/src/partitioner.rs')
s=p.read_text()
s=s.replace('Maximum queued cohort ledger rows','Maximum outstanding cohort ledger rows')
s=s.replace('/// Zero while queued in a live ledger; fixed after its first actual drain.\n    pub(crate) members: usize,','')
s=s.replace('worker: u64, bytes: usize','worker: Arc<()>, bytes: usize')
s=s.replace('    pub(crate) pressure_admissions: u64,','    pressure_admissions: u64,\n    admitted_unkeyed_bytes: u64,\n    closed: bool,')
s=s.replace('pressure_admissions: 0 }','pressure_admissions: 0, admitted_unkeyed_bytes: 0, closed: false }')
s=s.replace('        let leaders = cluster.leaders.get(topic)?;','        if self.closed { return None; }\n        let leaders = cluster.leaders.get(topic)?;')
s=s.replace('let info = row.filter(|_| !reset && !self.exhausted).and_then(|row| row.info.as_ref());','let info = row.filter(|_| !reset && !self.exhausted).and_then(|row| row.info.as_ref()).filter(|info| {\n            self.cohorts.len() < self.config.max_cohorts || row.is_some_and(|row| !self.full(topic, row.lifetime, info.partition))\n        });')
s=s.replace('worker: u64, record_bytes','worker: &Arc<()>, record_bytes')
s=s.replace('c.worker == worker','Arc::ptr_eq(&c.worker, worker)')
s=s.replace(', members: if tracked { 0 } else { 1 }','')
s=s.replace('if self.exhausted { return; }','if self.exhausted || self.closed { return; }')
s=s.replace('worker: u64, unkeyed: bool','worker: &Arc<()>, unkeyed: bool')
s=s.replace('if unkeyed && self.topics.get(topic).is_some_and(|row| row.info.is_none())','if unkeyed && plan.tag.id != 0 && self.topics.get(topic).is_some_and(|row| row.info.is_none())')
s=s.replace('        } else if unkeyed {\n            self.rng = Self::draw(self.rng).0;\n        }','        }\n        if unkeyed && plan.tag.id == 0 {\n            self.rng = Self::draw(self.rng).0;\n            if let Some(row) = self.topics.get_mut(topic) { row.info = None; }\n        }')
s=s.replace('} else if let Some(row) = self.topics.get(topic) {','} else if let Some(lifetime) = self.topics.get(topic).map(|row| row.lifetime) {')
s=s.replace('lifetime: row.lifetime, partition, worker,','lifetime, partition, worker: Arc::clone(worker),')
s=s.replace('        if unkeyed { if let Some(row)', '        if unkeyed { self.admitted_unkeyed_bytes = self.admitted_unkeyed_bytes.saturating_add(u64::try_from(plan.delta).unwrap_or(u64::MAX)); if let Some(row)')
s=s.replace('self.cohorts.get(&tag.id).map_or(tag.members.max(1), |c| c.members)','self.cohorts.get(&tag.id).map_or(1, |c| c.members)')
s=s.replace('    pub(crate) fn clear(&mut self) { self.topics.clear(); self.cohorts.clear(); self.topic_bytes = 0; }\n    pub(crate) fn counts(&self) -> (usize, usize, usize, u64) { (self.topics.len(), self.cohorts.len(), self.topic_bytes, self.pressure_admissions) }','    /// Seal on the first actual drain, preserving outstanding membership through retries.\n    pub(crate) fn drain(&mut self, tag: StickyTag, cluster: &Cluster) {\n        let topic = self.cohorts.get_mut(&tag.id).map(|c| { c.sealed = true; Arc::clone(&c.topic) });\n        if let Some(topic) = topic { self.maybe_rotate(&topic, cluster); }\n    }\n    pub(crate) fn clear(&mut self) { self.closed = true; self.topics.clear(); self.cohorts.clear(); self.topic_bytes = 0; }\n    pub(crate) fn counts(&self) -> (usize, usize, usize, u64, u64) { (self.topics.len(), self.cohorts.len(), self.topic_bytes, self.pressure_admissions, self.admitted_unkeyed_bytes) }')
p.write_text(s)
